labexp/osmtracker-android

src/me/guillaumin/android/osmtracker/gpx/ExportTrackTask.java
src/me/guillaumin/android/osmtracker/util/FileSystemUtils.java

As discussed, here's the merge request with the code changes I originally proposed. To avoid future uses of the file handling routines suffering from the same bug, I have documented the requirement to perform a media scan after calling one of the methods in question.
On a side note: at first glance, it looked like `MediaScannerConnection.scanFile(file, mimeType)` could solve all our problems by scanning a single file without requiring a context – alas, it requires an instance of `MediaScannerConnection`, whose constructor requires – guess what – a `Context`.

[issue #261] Run media scanner on all exported files

---

README.md

This PR only add to the README file the URL of the official source code repository of OSM Tracker.

source code repository URL to README

---

app/src/main/java/org/osmtracker/osm/OpenStreetMapConstants.java

This PR intend to fix the error mentioned in issue #137:
This error appears in **OpenStreetMapConstants** class
Line with error:  
```Java
private static final String OSM_API_URL_DEV = "http://master.apis.dev.openstreetmap.org";  
private static final String OSM_API_URL_PROD = "http://www.openstreetmap.org";
```
The solution is to change from `http` to `https` in both lines:  
```Java
private static final String OSM_API_URL_DEV = "https://master.apis.dev.openstreetmap.org";  
private static final String OSM_API_URL_PROD = "https://www.openstreetmap.org";
```

Fix when upload GPX data to OSM (error 500)

---

app/src/main/java/net/osmtracker/OSMTracker.java
app/src/main/java/net/osmtracker/activity/Preferences.java
app/src/main/java/net/osmtracker/service/gps/GPSLogger.java
app/src/main/res/values-de/strings-preferences.xml
app/src/main/res/values/strings-preferences.xml
app/src/main/res/xml/preferences.xml

I found it would be useful to have kind of a "motion detection" to avoid polluting the track with redundant points while the user is standing still. The PR implements this in a most simple way by using Android LocationManager.requestLocationUpdates's parameter "minDistance". A new preference has been introduced to set the threshold (value in meters):
Settings -> GPS logging distance

Motion detection/minimum distance between subsequent track points

---

.travis.yml
app/build.gradle
app/src/androidTest/assets/gpx/gpx-test.gpx
app/src/androidTest/java/net/osmtracker/test/gpx/ExportTrackTaskTest.java
gradle/wrapper/gradle-wrapper.properties

This PR includes:
* ExportTrackTaskTest fixed on Android API 21+. (lower versions of the API aren't supported because the testInstrumentationRunner is not available).
* Gradle 4.6-all checksum was updated
* Travis was set to run on android 21, using tools 28.0.3.

Fix travis CI

---

app/src/main/java/net/osmtracker/activity/ButtonsPresets.java
app/src/main/java/net/osmtracker/activity/TrackLogger.java
app/src/main/java/net/osmtracker/layout/DownloadCustomLayoutTask.java

This PR try to solve the issue #183. I changed/separated the path where the layouts and the gpx files are stored (always keeping the default path to both but when it's changed in the settings screen, more specific, under **GPX settings** section, only the Custom Layouts files keep this path).
**Notice**: the default path is */osmtracker* (either in the internal or external storage).

Fix issue 183

---

app/src/main/AndroidManifest.xml
app/src/main/java/net/osmtracker/activity/DisplayTrack.java
app/src/main/java/net/osmtracker/activity/DisplayTrackMap.java
app/src/main/java/net/osmtracker/activity/TrackManager.java
app/src/main/res/xml/preferences.xml

In this PR is added a method which sets the osmdroid HTTP User Agent to the application's package name. This avoid using the osmdroid default user agent (banned in osm servers). More info [here](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library). 
This PR fixes the issue #194 and #195.
Note: Travic Ci will fail since this PR is based on develop branch as it is now (before the eventual merge of #202)

fix display of background maps

---

app/src/main/java/net/osmtracker/activity/TrackLogger.java

Now it asks if the tag exists before adding it. Fixes #189

Fix issue  #189, adding multiple tags to track

---

app/src/main/java/net/osmtracker/activity/TrackManager.java

This PR solves issue #167 
To upload a trace properly to OSM, the app needs **storage permission** for reading the **gpx file**.
**Functionality added:**
Every time a user tries to upload or export a trace, he/she will be asked to deny or allow the app access the storage. This, only if the permissions aren't granted yet. 
Android versions tested on: 6.0 and 8.0

Fix upload trace osm (issue #167)

---

app/src/main/java/net/osmtracker/activity/DisplayTrackMap.java

This PR was created instead of [this PR](https://github.com/labexp/osmtracker-android/pull/192) originally created by @icrf2000. 
It improves the visualization in the map as shown in the following picture.
- The image at the **left** shows the map with the changes of this PR
- The image at the **right** shows how the map looks like without this PR

Map scale up

---

app/src/main/java/net/osmtracker/activity/DisplayTrackMap.java
app/src/main/res/xml/preferences.xml

This PR fix issue #96, #125, #127 
The options `CycleMap` and `MapQuest` are not available any more for using them in the app.
The only source available that woks in the same way is MAPNIK so we decided that, by the moment, the app will use by default the MAPNIK tile source. If this is the best for the app and users, we can let this change be permanent.
With this PR the map tile source can not be changed. This is for avoiding exceptions and because MAPNIK will be used anyway if the selected source does not work correctly (throws an exception) and this will happen if `MapQuest` or `CycleMap` are chosen.
In conclusion the functionality of choosing the map tile source was useless right now.

Avoid choosing the MapTileSource in app preferences. Let Mapnik by default.

---

app/src/main/java/net/osmtracker/activity/TrackManager.java

Now it should only start the TrackLogger Activity if GPS permission is granted.

Request GPS permission before start TrackLogger Activity, fix issue #207

---

app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java
app/src/main/res/values/strings.xml

In the TrackDetail activity, the `export as gpx` button shows a dialog while does the task but when the track is small this dialog appears very shortly and the app says nothing after it disappears. This PR notifies when gpx export finishes showing a Toast.

Fix issue #122

---

app/src/main/java/net/osmtracker/activity/TrackDetailEditor.java
app/src/main/java/net/osmtracker/activity/TrackManager.java
app/src/main/java/net/osmtracker/gpx/ExportToStorageTask.java
app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java

Avoid dates duplication in directories name and gpx files-name when exporting without changing the track names manually.
This happens anytime you export a track without editing it's name.
MIght be related to issues #161 and #162.

Fix gpx filename

---

app/src/main/res/menu/tracklogger_menu.xml

Changing the `app` attribute in tracklogger_menu.xml and using `android` instead solves the issue #235

Save button doesn't appear in tracklogger activity

---

app/src/test/java/net/osmtracker/util/ThemeValidatorTest.java

The **ThemeValidatorTest** class is included in the PR, different tests where added for the purpose of checking if any given theme via paramater is included on the array I made (which is basically the same as the one in the resource values _"values-preferences.xml"_ ). However there is a slight error when using a invalid theme value for example `net.osmtracker:style/YellowTheme`, the mocked shared preferences is not compatible with  line 36 `Editor e = prefs.edit();` of ThemeValidator.
Would be great if there is any way to make the mocked prefs sustainable to a `.edit` method and not making a Null interface of _AndroidSharedPreference.Editor_.

Including ThemeValidatorTest 

---

app/src/androidTest/java/net/osmtracker/layouts/DeleteLayoutTest.java

This PR fix the fail when the test is runned for the first time.  The problem is the setup method cannot create the mock layout because is called "before the class", without permissions to write. 
The solution is moving the code from the `setup` method to a `beforeActivityLaunched()` that overrides a method from `ActivityTestRule`, now the "setup code" is runned when the the class is instantiated but before the activity is launched.

Fix Delete Layout Test

---

.travis.yml
app/build.gradle
app/src/androidTest/java/net/osmtracker/layouts/DownloadLayoutTest.java
app/src/androidTest/java/net/osmtracker/layouts/RepositorySettingsDialogTest.java
app/src/main/AndroidManifest.xml

This PR upgrades to target Android 10 (API level 29) to fulfill Google Play requirements.  Android version on Travis tests were upgraded too, with some fixes on instrumentation tests due to this changes. Finally, disable scoped storage (see issue #259)

Targetsdk update 

---

app/src/main/java/net/osmtracker/activity/TrackDetailEditor.java
app/src/main/java/net/osmtracker/gpx/ExportToStorageTask.java
app/src/main/java/net/osmtracker/gpx/ExportToTempFileTask.java
app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java
app/src/main/java/net/osmtracker/util/FileSystemUtils.java
app/src/test/java/net/osmtracker/gpx/ExportTrackTest.java
app/src/test/java/net/osmtracker/gpx/export/BuildGPXFilenameTest.java
app/src/test/java/net/osmtracker/util/UnitTestUtils.java

- Doesn't append the start date to the track's name after editing
- Validate duplicated files and directories when exporting 
- Follow the output gpx format specified in preferences 
- Add unit tests for the gpx filename building
- Add utility method for encapsulating Date objects building (weird modifications need to be made)
- Split some too long methods into smaller ones

Test build gpx filename

---

.gitignore
app/src/main/java/net/osmtracker/activity/TrackDetailEditor.java
app/src/main/java/net/osmtracker/db/DataHelper.java
app/src/main/java/net/osmtracker/db/TrackContentProvider.java
app/src/main/java/net/osmtracker/db/TracklistAdapter.java
app/src/main/java/net/osmtracker/db/model/Point.java
app/src/main/java/net/osmtracker/db/model/Track.java
app/src/main/java/net/osmtracker/db/model/TrackPoint.java
app/src/main/java/net/osmtracker/db/model/WayPoint.java
app/src/main/java/net/osmtracker/gpx/ExportToStorageTask.java
app/src/main/java/net/osmtracker/gpx/ExportToTempFileTask.java
app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java
app/src/main/res/xml/preferences.xml
app/src/test/assets/gpx/gpx-test.gpx
app/src/test/java/net/osmtracker/data/GPXMocks.java
app/src/test/java/net/osmtracker/data/MockDataHelper.java
app/src/test/java/net/osmtracker/data/TrackMocks.java
app/src/test/java/net/osmtracker/data/TrackPointMocks.java
app/src/test/java/net/osmtracker/data/WayPointMocks.java
app/src/test/java/net/osmtracker/gpx/ExportTrackTest.java
app/src/test/java/net/osmtracker/test/db/model/TrackTest.java

The main goal of this PR is to simplify the way GPX files are created, to make easier introducing unit tests and make the code more legible for promote more users collaboration. 
This PR includes a refactor of `ExportTrackTask` and adds junit tests in `ExportTrackTaskTest`. Access to DB or content provider was encapsulated in `DataHelper` for net.osmtracker.gpx package, model objects (net.osmtracker.db.model.*) are passed as result of the queries. 
Minor changes:
* `TrackDetailEditor`, `TrackListAdapter`: change in method name.
* `main/res/xml/preferences.xml`: change in indentation of `ListPreference` element in favor of legibility.
Also this PR uniforms the way compass values are exported to the GPX File in a *comment*, they are now written with the format:
~~~
<cmt><![CDATA[compass …

Simplification of GPX files export (creation)

---

app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java
app/src/test/java/net/osmtracker/data/TrackMocks.java

`ExportTrackTask` was using `track.getStartDate()` for building the GPX Filename. `startDate` value is taken from the first waypoint recorded in the track, the bug appears when Track has no waypoints because the`startDate` value will be null (as is null the `endDate`). To fix this bug the `buildGPXFilename()` is changed to use the `track.getTrackDate()` value. `trackDate` will never be null.

Fix ExportTrackTask

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/net/osmtracker/activity/Preferences.java
app/src/main/java/net/osmtracker/activity/TrackLogger.java
app/src/main/java/net/osmtracker/activity/TrackManager.java
app/src/main/java/net/osmtracker/layout/GpsStatusRecord.java
app/src/main/java/net/osmtracker/listener/TagButtonOnClickListener.java
app/src/main/java/net/osmtracker/service/gps/GPSLogger.java
app/src/main/java/net/osmtracker/service/gps/GPSLoggerServiceConnection.java
app/src/main/res/xml/preferences.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

This pull request includes changes to the project, focusing on updating the API level and adding changes necessary for proper operation after the new targetSDK. Key changes include updating the SDK versions, adding a new permission for foreground services and improving the code for button layout preferences and broadcast intents.
* Updated `compileSdk` and `targetSdkVersion` to 35 in `app/build.gradle`.
* Added `org.apache.commons:commons-io:1.3.2` to dependencies in `app/build.gradle`. This is for the successful execution of DownloadLayoutTest and DeleteLayoutTest.
* Upgraded Gradle distribution to `8.10.1` in `gradle-wrapper.properties`.
* Added `FOREGROUND_SERVICE_LOCATION` permission in `AndroidManifest.xml`.
* Added explicit execution of the buttons presets window in …

Updating the target SDK to 35 with the necessary changes in dependencies, permissions and execution flows

---

app/src/main/java/net/osmtracker/activity/TrackManager.java

* Fix: #476 
The “Resume tracking” btn should execute the setActiveTrack function only when the app has no active tracking.

Fix #476: Resume tracking btn change the state to stopped

---

app/src/main/java/net/osmtracker/activity/Intro.kt

Background color added for intro activity. Now we have a consistent color for cellphones with the dark or light mode on.
See the comment https://github.com/labexp/osmtracker-android/commit/431b7f3b7b67b7f6029989078c92f9853ad4ad30#r150085284 for more information
> ... with the update to `com.github.AppIntro:AppIntro` we have to set the background to match the light / dark theme. At the moment our intro has a light background when the phone has dark mode off.

Added background color for intro activity

---

app/src/main/java/net/osmtracker/activity/TrackDetail.java
app/src/main/java/net/osmtracker/activity/TrackManager.java
app/src/main/res/values/strings.xml

Hi! This PR addresses issues #479 and #480
**Modifications**
* #479 
Added a new check to prevent adding a divider multiple times.
* #480 
The request of storage permission was moved to a new private reusable method `writeExternalStoragePermissionGranted()`.
His implementation adds a new check to validate new android SDKs and a new `AlertDialog` if the permission is not granted.
---
Finally, coded strings have been replaced by @string resources to improve localization and maintenance.

Fix DividerItemDecoration duplication and GPX export issues (#479 #480)

---

app/src/main/java/net/osmtracker/activity/TrackManager.java
app/src/main/res/drawable/divider.xml

solution to the issue:
* #311 
a white dividing line has been added so that the division of each trace can be clearly seen.

Fix visibility of horizontal dividers in TrackManager (Issue #311)

---

app/src/main/java/net/osmtracker/activity/TrackDetail.java

This pull request includes a change to the `TrackDetail` activity in the Android application to fix a bug related to the display of the OSM upload date.
Bug fix:
* [`app/src/main/java/net/osmtracker/activity/TrackDetail.java`](diffhunk://#diff-92a4f5de89e4668a325d4625e957ebc21fa22ccd8d7a3d56396951b82495eeabL184-R184): Corrected the column used to fetch the OSM upload date in the `onResume` method to display the correct date.
issue resolved:
* #314

fix “Uploaded to OpenStreetMap” always reported as “1 Jan 1970 01:00:00” #314

---

app/src/main/java/net/osmtracker/activity/AvailableLayouts.java
app/src/main/res/layout/tracklist_item.xml
app/src/main/res/values-pl/strings.xml

This PR addresses the issue mentioned in #347, where the problem was related to the size of the text when the largest text size setting is activated on the phone. Thanks to @miltonials, we confirmed that the problem mentioned in the PR was already solved with a scroll. However, during testing, we identified additional issues.
**First problem**
In the track manager the text for date, name, trackpoints and waypoints was to big for his container.
**Example of the problem**
**How i solved it**
- I added two possible text sizes
- For normal text size settings, the appearance remains unchanged.
- For the largest text size setting, the text increases, but not excessively.
- I adjusted the trackpoints and waypoints labels to display vertically, improving the app's overall look and resolving the …

Text Size and Layout Adjustments for Large Text Setting Compatibility

---

app/src/main/java/net/osmtracker/OSMTracker.java
app/src/main/java/net/osmtracker/gpx/ExportToTempFileTask.java
app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java
app/src/main/res/values/strings-preferences.xml
app/src/main/res/values/values-preferences.xml
app/src/main/res/xml/preferences.xml
app/src/test/java/net/osmtracker/gpx/ExportToStorageTaskTest.java

* This PR is an extended feature of issue #333 according to #470.
It allows the user to add a custom suffix label to the name of GPX files when sharing.
In `Settings > GPX Settings`, the option **"Export label for sharing files"** allows the user to customize the suffix of a track for export as a `.gpx` file. The exported file will follow the format:  
`YYYY-MM-DD_hh-mm-ss_EXPORT_LABEL`, where `_EXPORT_LABEL` defaults to `_OSMTracker`.

Customized export label for file sharing (#333, #470)

---

app/src/main/java/net/osmtracker/activity/TrackManager.java
app/src/main/java/net/osmtracker/db/DataHelper.java
app/src/main/java/net/osmtracker/gpx/ExportToTempFileTask.java
app/src/main/java/net/osmtracker/gpx/ZipHelper.java
app/src/main/res/values/strings.xml

This update enhances the GPX sharing functionality by introducing the ability to share traces as a ZIP file when associated files (e.g., images or other media) are present. If no associated files are detected, the trace is shared as a standard GPX file. This improvement ensures better handling of additional trace data and facilitates seamless sharing of complete trace information.
This feature was implemented in collaboration with [@Kevin-Salazar-itcr](https://github.com/Kevin-Salazar-itcr) and [@FR3DD221](https://github.com/FR3DD221)

Improved GPX Sharing: Share as ZIP

---

app/src/main/res/layout/trackdetail.xml
app/src/main/res/layout/tracklist_item.xml

Addressing layout breaks and text scaling issues when users modify system display and text size settings.
**Track List Item Layout**
- Replaced RelativeLayout with more flexible LinearLayout
- Implemented dynamic text scaling using autoSizeTextType
- Increased maximum text auto-sizing from 14sp to 20sp
- Improved text appearance consistency
- Enhanced vertical spacing and alignment
- Removed redundant margin and padding attributes
**Waypoint List Item Layout**
- Migrated from RelativeLayout to ConstraintLayout
- Implemented responsive positioning using constraints
- Removed hard-coded right margins
- Ensured dynamic text scaling and alignment
**How it looks with the display and text on the biggest size**
**How it looks with the display and text on the medium size**
This is a fix of PR …

UI Responsiveness Improvements for Track and Waypoint List Layouts

---

app/src/main/java/net/osmtracker/activity/Preferences.java
app/src/main/java/net/osmtracker/activity/WaypointList.java
app/src/main/res/layout-iw/waypointlist_item.xml
app/src/main/res/layout/about.xml
app/src/main/res/layout/available_layouts.xml
app/src/main/res/layout/buttons_presets.xml
app/src/main/res/layout/displaytrackmap.xml
app/src/main/res/layout/github_repository_settings.xml
app/src/main/res/layout/gpsstatus_record.xml
app/src/main/res/layout/osm_upload.xml
app/src/main/res/layout/tracklogger.xml
app/src/main/res/layout/trackmanager.xml
app/src/main/res/layout/waypointlist_item.xml
app/src/main/res/xml/preferences.xml

- Added `android:fitsSystemWindows="true"` to handle system window insets properly
- Ensures content is properly displayed without being obscured by the status bar
Verified on:
- Android 15 (API 35) - Fixed
- Android 7.1 (API 25) - No regression

fix: Add fitsSystemWindows to handle edge-to-edge behavior in Android 15

---

app/src/main/java/net/osmtracker/OSMTracker.java
app/src/main/res/xml/preferences.xml
app/src/test/java/net/osmtracker/gpx/ExportToStorageTaskTest.java

This PR addresses the issue where the tag assigned to exported tracks is inconsistent, leading to unexpected behavior for users who update the app from the Play Store. By setting the tag to "", exported and shared tracks will behave consistently across updates, ensuring a seamless experience for users.
Changes Made
* Set the tag for exported tracks to "" to ensure it remains consistent and doesn't change unexpectedly after updates.
* Verified that users updating the app via the Play Store will not experience any changes in track export behavior.
solution to the issue:
* #515 
note: the test has also been updated

Fix inconsistent tag behavior for exported tracks to ensure Play Store update consistency

---

app/src/main/java/net/osmtracker/activity/WaypointList.java
app/src/main/res/values/strings.xml

This pr fixes the bug that happens in android 13, that does not allow to visualize the images because it does not have an application that can read the images.
Issue:
* #554

fix: Waypoint preview does not work

---

app/src/main/java/net/osmtracker/activity/GitHubUpload.java
app/src/main/java/net/osmtracker/util/Callback.java
app/src/main/java/net/osmtracker/util/GitHubUtils.java
app/src/main/res/values-es/strings.xml

[comment]: # (Thank you for your contribution! Please fill out the following details to help us review your pull request.)
[comment]: # (Provide a clear explanation of the changes in this PR)
[comment]: # (Include information about what problem it solves, how it is implemented, and if it affects UI/API)
This PR introduces the capacity to upload the trace zip file to a GitHub repository without the need to change the filename.
Example: if we upload a file with the following:
* **Trace name**: myTrace.gpx
* **Zip file name**: myTrace.zip
In the first attempt to upload the trace, the file will have `myTrace.zip` as name, but in the second attempt his name will change to `myTrace(1).zip`. Finally the target repository will have two files `myTrace.zip` and `myTrace(1).zip`.
_Note: the number …

An easy way to upload the same filename to GitHub

---

app/src/main/java/net/osmtracker/GitHubUser.java
app/src/main/java/net/osmtracker/activity/GitHubConfig.java
app/src/main/java/net/osmtracker/activity/GitHubNewFork.java
app/src/main/java/net/osmtracker/activity/GitHubNewRepo.java
app/src/main/java/net/osmtracker/activity/GitHubPullRequest.java
app/src/main/java/net/osmtracker/activity/GitHubUpload.java
app/src/main/java/net/osmtracker/github/GitHubConstants.java
app/src/main/res/values/strings.xml

[comment]: # (Thank you for your contribution! Please fill out the following details to help us review your pull request.)
[comment]: # (Provide a clear explanation of the changes in this PR)
[comment]: # (Include information about what problem it solves, how it is implemented, and if it affects UI/API)
This PR improves how OSMTracker is managing the github links, user messages adding R strings, retrieving repositories message and specific error messages for PRs.
[comment]: # (Link to the original bug report or related work in list format, if applicable)
[comment]: # (* Closes: #number)
[comment]: # (* Related to: #number)
This PR is not related to a specific issue. But is needed to keep a structured code for the next release.
##
[comment]: # (Please confirm the following before …

Improvement of strings and message in upload to GitHub functionality

---

.github/workflows/nightly.yml

[comment]: # (Include information about what problem it solves, how it is implemented, and if it affects UI/API)
This PR improves the nightly GitHub action, running it only when, in the last 24 hours, new code is committed to the develop branch. Also, attempt to delete the nightly build release only when it exists.
Closes: #606 
##
[comment]: # (Please confirm the following before submitting your PR)
[comment]: # (To check a task please put a "x" inside the `[]`)
[comment]: # ([ ] : not done)
[comment]: # ([x] : done)
[comment]: # (Make sure how your PR looks clicking the "Preview" tab at the top of this editor)

Avoids building nightly APK when no changes in develop code
