app/src/main/java/me/guillaumin/android/osmtracker/db/DataHelper.java
app/src/main/java/me/guillaumin/android/osmtracker/db/DatabaseHelper.java

Dear developers,
I edited the code to fix the two resource leaks reported in issue #74 
Please let me know if there are any problems. @nguillaumin 
Thanks.

fix potential database cursor leaks 

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/net/osmtracker/service/gps/GPSLogger.java
build.gradle

This PR fixes notifications and set highcontrast theme, both in android 8. Also change the apply plugin syntax in gradle (the change will help building for fdroid).

Minor fixes

---

CONTRIBUTING.md
README.md

The develop branch is some commits behind master.

Updating develop branch

---

app/src/main/java/net/osmtracker/db/TracklistAdapter.java
app/src/main/res/layout/tracklist_item.xml
app/src/main/res/layout/trackmanager.xml

Problem fixed: When have too many tracks and you scroll all over them eventually some track-status-icons disappear.
I have tested with all the icons and some at the same time. It works fine.
This PR fix the issue #113

Fix: Upload-track-icon does not dissapear when scrolling any more.

---

app/src/main/java/net/osmtracker/view/TextNoteDialog.java

Open keyboard automatically when creating a note

---

app/src/main/java/net/osmtracker/activity/TrackLogger.java

This PR fix the problem that deletes the tags saved before save the trace. Issue #170

The bug that deletes the saved tags before save the trace is solved

---

app/src/main/java/net/osmtracker/service/gps/GPSLogger.java

when creating a WPT, also create corresponding TRKPT

---

app/src/main/res/values-de/strings.xml

add missing whitespace in german string

---

app/src/main/java/net/osmtracker/activity/TrackManager.java

Default track names are now following ISO 8601

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/res/menu/tracklogger_menu.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Add kotlin support for the project.
Dependencies and plugins added in gradle file.
Important to have an version greater than 3.0 of Android Studio.
Implements solution for issue #228

Add kotlin

---

app/src/main/java/net/osmtracker/OSMTracker.java
app/src/main/java/net/osmtracker/activity/Preferences.java
app/src/main/java/net/osmtracker/activity/TrackLogger.java
app/src/main/java/net/osmtracker/db/DataHelper.java
app/src/main/java/net/osmtracker/db/DatabaseHelper.java
app/src/main/java/net/osmtracker/db/TrackContentProvider.java
app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java
app/src/main/java/net/osmtracker/listener/PressureListener.java
app/src/main/java/net/osmtracker/service/gps/GPSLogger.java
app/src/main/res/values/strings-preferences.xml
app/src/main/res/xml/preferences.xml

This PR contains only the functionality to record barometric pressure (See PR #217)

Icrf2000 hz04 barometer

---

app/src/main/java/net/osmtracker/OSMTracker.java
app/src/main/java/net/osmtracker/activity/Preferences.java
app/src/main/java/net/osmtracker/activity/TrackLogger.java
app/src/main/java/net/osmtracker/db/DataHelper.java
app/src/main/java/net/osmtracker/db/DatabaseHelper.java
app/src/main/java/net/osmtracker/db/TrackContentProvider.java
app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java
app/src/main/java/net/osmtracker/listener/PressureListener.java
app/src/main/java/net/osmtracker/service/gps/GPSLogger.java
app/src/main/res/values/strings-preferences.xml
app/src/main/res/xml/preferences.xml

See #216
It is a first version, just in case anybody finds it interesting. 
- Only tested on Android 8.1 Galaxy Nexus 6P
- No idea how it behaves on devices without barometric pressure sensor
- Not yet possible to switch recording of pressure on/off. Would be better if this were possible, maybe it impacts power consumption.

 log barometric pressure

---

app/src/main/java/net/osmtracker/util/CustomLayoutsUtils.java
app/src/test/assets/gpx/gpx-test.gpx
app/src/test/java/net/osmtracker/util/CustomLayoutsUtilsTest.java

This PR helps to fix  https://github.com/labexp/osmtracker-android/issues/243

Add CustomLayoutsUtilsTest

---

app/build.gradle

This downgrade allow traces to be uploaded to OSM.
Fix issue #258

Downgrade the apache dependency to 4.3.6

---

app/src/androidTest/java/net/osmtracker/layouts/DeleteLayoutTest.java
app/src/androidTest/java/net/osmtracker/layouts/DownloadLayoutTest.java
app/src/androidTest/java/net/osmtracker/util/TestUtils.java
app/src/androidTest/java/net/osmtracker/util/ToastMatcher.java

Adds an instrumentation test for downloading a layout

First test to download layouts

---

app/src/main/java/net/osmtracker/activity/Preferences.java
app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java
app/src/main/java/net/osmtracker/listener/PressureListener.java

I tested recording a trace with the log barometric pressure option selected and unselected, when the option is selected the data is stored and exported in the gpx file, when it isn't that doesn't happen

Barometer sensor

---

app/src/main/AndroidManifest.xml
app/src/main/java/net/osmtracker/activity/OpenStreetMapUpload.java
app/src/main/java/net/osmtracker/activity/TrackDetailEditor.java
app/src/main/java/net/osmtracker/activity/TrackManager.java
app/src/main/java/net/osmtracker/db/DataHelper.java
app/src/main/java/net/osmtracker/gpx/ExportToTempFileTask.java
app/src/main/java/net/osmtracker/gpx/ExportTrackTask.java
app/src/main/java/net/osmtracker/osm/UploadToOpenStreetMapTask.java
app/src/main/res/menu/trackmgr_contextmenu.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/filepaths.xml

This PR includes the changes requested on the review of [PR 252](https://github.com/labexp/osmtracker-android/pull/252) and also rebase develop to avoid conflicts indicated in the original PR. Due the rebase is easier to open a new PR.

Sharing feature v2 (PR#252)

---

app/src/main/java/net/osmtracker/db/DatabaseHelper.java

Solution proposed by @icrf2000 for the issue #279.

Set DB version to 17 and manage the upgrade (Resolves #279)

---

app/src/main/AndroidManifest.xml

Updates version code and name.

Version code 51, version name v1.0.0beta3

---

app/src/main/AndroidManifest.xml

Fix #299. 
New version uploaded to google play for open testing.

v1.0.0 beta4a

---

app/src/main/res/layout/available_layouts.xml
gradle/wrapper/gradle-wrapper.properties

Add a simple scrollview to make the "Available layouts" view scrollable. Yes there are too much buttons for my screen.
https://github.com/user-attachments/assets/78c2d949-9532-480d-9728-7a4a4d688568

Scrollview available layouts

---

.github/workflows/android.yml

Setup simple GitHub workflow to build and run tests

Add GitHub Android Workflow

---

.github/workflows/nightly.yml

Workflow nightly

---

.github/workflows/android.yml
app/build.gradle
app/src/main/java/net/osmtracker/activity/DisplayTrackMap.java

Upgrade osmdroid from 6.1.5 to 6.1.20

---

app/src/main/java/net/osmtracker/activity/TrackLogger.java

Fix 468 photo images not saved in osmfolder

---

app/build.gradle
app/jacoco.gradle
app/src/main/java/net/osmtracker/activity/Intro.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties

Upgrade as many libs as possible.

Upgrade libs

---

fastlane/metadata/android/en-US/changelogs/66.txt

Changelog added according to the last changes for the 2025.05 fix version

Add changelog for version 66
